ci:
  autoupdate_schedule: quarterly
  autofix_prs: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: double-quote-string-fixer
      - id: debug-statements
      - id: mixed-line-ending
  - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.3.5
      hooks:
        # Run the linter.
        - id: ruff
          args: [ --fix ]
        # Run the formatter.
        - id: ruff-format
