# Dev environment
name: cmip6-leap-feedstock-maintenance
channels:
  - conda-forge
dependencies:
  # - python=3.9.13 # see https://github.com/pangeo-forge/pangeo-forge-runner/issues/78
  - python=3.10
  - ipykernel
  - gcsfs
  - fsspec
  - pandas
  - jupyterlab
  - zarr
  - dask
  - distributed
  - ipywidgets
  - pip
  - pip:
      - snakeviz
      # - leap-data-management-utils #TODO add later for now install manually
