# Dev environment
name: cmip6-leap-feedstock
channels:
  - conda-forge
dependencies:
  - python=3.9.13 # see https://github.com/pangeo-forge/pangeo-forge-runner/issues/78
  # - python=3.10
  - ipykernel
  - gcsfs
  - fsspec
  - apache-beam-with-gcp==2.42.0
  - pandas
  - jupyterlab
  - zarr
  - dask
  - distributed
  - ipywidgets
  - pip
  - pip:
      - google-cloud-bigquery
      - gcsfs
      - git+https://github.com/pangeo-forge/pangeo-forge-runner.git@main
      - git+https://github.com/pangeo-forge/pangeo-forge-recipes.git@main
      - db_dtypes
      - pangeo-forge-esgf
      - snakeviz
