name: New File Request
description: Propose a list of CMIP6 datasets to be ingested to the cloud.
title: "[REQUEST]: "
labels: ["request"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for using the Pangeo CMIP6 cloud data and making a request for additional data.
        Please paste a list of strings like this in the field below:
        ```
        'CMIP6.CMIP.CSIRO-ARCCSS.ACCESS-CM2.historical.r1i1p1f1.SImon.sifb.gn.v20200817',
        'CMIP6.CMIP.CSIRO-ARCCSS.ACCESS-CM2.historical.r2i1p1f1.SImon.sifb.gn.v20200817',
        'CMIP6.CMIP.CSIRO-ARCCSS.ACCESS-CM2.historical.r3i1p1f1.SImon.sifb.gn.v20200817',
        'CMIP6.CMIP.CSIRO-ARCCSS.ACCESS-CM2.historical.r4i1p1f1.SImon.sifb.gn.v20210607',
        'CMIP6.CMIP.CSIRO-ARCCSS.ACCESS-CM2.historical.r5i1p1f1.SImon.sifb.gn.v20210607',
        ```
        You can use [pangeo-forge-esgf](https://github.com/jbusecke/pangeo-forge-esgf#parsing-a-list-of-instance-ids-using-wildcards) to make your life easier here.

        > ⚠️ Please include the commas at the end to make this easier to copy and paste.

  - type: textarea
    id: file_list
    attributes:
        label: List of requested idds
        render: markdown
    validations:
        required: true
  - type: textarea
    id: comments
    attributes:
      label: Description
      description: >
        We cannot promise to deliver datasets on any timeline, but if you are looking to publish a paper soon, please make sure to mention it here, and we will do our best to process this request.
