name: Deploy recipes

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [opened, reopened, synchronize, labeled]
  schedule:
    - cron: "0 * * * SUN" # run every sunday

jobs:
  deploy-recipes:
    name: deploy-recipes
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: "Authenticate to Google Cloud"
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_DATAFLOW_SERVICE_KEY }}"
      - name: "Deploy recipes PR"
        if: ${{ github.event_name == 'pull_request' }}
        uses: "pangeo-forge/deploy-recipe-action@v0.2"
        with:
          select_recipe_by_label: "" #to circumvent https://github.com/leap-stc/cmip6-leap-feedstock/issues/6#issuecomment-1668577971
          pangeo_forge_runner_config: "./configs/config-pgf-runner-leap-dataflow-pr.json"
        env:
          IS_TEST: true
          GOOGLE_APPLICATION_CREDENTIALS: "${{ steps.auth.outputs.credentials_file_path }}"
      - name: "Deploy recipes Production"
        if: ${{ github.event_name != 'pull_request' }}
        uses: "pangeo-forge/deploy-recipe-action@v0.2"
        with:
          select_recipe_by_label: "" #to circumvent https://github.com/leap-stc/cmip6-leap-feedstock/issues/6#issuecomment-1668577971
          pangeo_forge_runner_config: "./configs/config-pgf-runner-leap-dataflow.json"
        env:
          IS_TEST: false
          GOOGLE_APPLICATION_CREDENTIALS: "${{ steps.auth.outputs.credentials_file_path }}"
