name: Deploy recipes

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [opened, reopened, synchronize, labeled]
  schedule:
    - cron: "0 */9 * * *" # run every 9 hours to move through time zones over time

jobs:
  deploy-recipes:
    name: deploy-recipes
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: "Authenticate to Google Cloud"
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_DATAFLOW_SERVICE_KEY }}"
      - name: "Deploy recipes"
        uses: "pangeo-forge/deploy-recipe-action@bump_dictobjs"
        with:
          select_recipe_by_label: "" #to circumvent https://github.com/leap-stc/cmip6-leap-feedstock/issues/6#issuecomment-1668577971
          pangeo_forge_runner_config: "./configs/config-pgf-runner-leap-dataflow.json"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${{ steps.auth.outputs.credentials_file_path }}"
