name: Flag Retractions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  remove-retractions:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: "Authenticate to Google Cloud"
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_DATAFLOW_SERVICE_KEY }}"
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        # TODO: base on an actual release
        run: python -m pip install tqdm httpx gcsfs git+https://github.com/leap-stc/leap-data-management-utils.git@factor-out-cmip
      - name: "Parse catalog"
        shell: bash
        run: |
          python scripts/retraction.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${{ steps.auth.outputs.credentials_file_path }}"
      - name: Upload-retraction-report
        uses: actions/upload-artifact@v3
        with:
          name: retraction-report
          path: "retraction-report.html"
