name: Flag Retractions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  remove-retractions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Authenticate to Google Cloud"
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_DATAFLOW_SERVICE_KEY }}"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        # TODO: base on an actual release
        run: python -m pip install tqdm httpx gcsfs git+https://github.com/leap-stc/leap-data-management-utils.git@factor-out-cmip
      - name: "Run retraction script"
        shell: bash
        run: |
          python scripts/retraction.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${{ steps.auth.outputs.credentials_file_path }}"

  rerun-failed-jobs:
      runs-on: ubuntu-latest
      needs: [remove-retractions]
      if: failure()
      steps:
        - name: Rerun failed jobs in the current workflow
          env:
            GH_TOKEN: ${{ github.token }}
          run: gh run rerun ${{ github.run_id }} --failed
